{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cortex.fullname" . }}-gateway-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}-gateway
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jwt_secret: {{ tpl (toYaml .Values.gateway.jwt_secret) . | b64enc}}
type: Opaque
{{- end }}